openapi: 3.0.1
info:
  title: Azure OpenAI Chat
  description: ''
  version: '1.0'
servers:
  - url: https://set-it-via-backend/openai
paths:
  /*:
    post:
      summary: OpenAI Chat
      operationId: chat
      responses:
        '200':
          description:
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]