openapi: 3.0.1
info:
  title: echo-test
  description: ''
  version: '1.0'
servers:
  - url: https://set-it-via-backend/openai
paths:
  /*:
    get:
      summary: openai-all
      operationId: openai-all
      responses:
        '200':
          description: 
    post:
      summary: openai-all-post
      operationId: openai-all-post
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
